
export const EVENT_TAB_ONCHANGE = 'EVENT_TAB_ONCHANGE'
export const EVENT_TABVIEW_BECOME_RESPONDER = 'EVENT_TABVIEW_BECOME_RESPONDER'
export const EVENT_SCENE_SCROLL_TOP = 'EVENT_SCENE_SCROLL_TOP'
export const EVENT_CONTAINER_GESTURE_ACTIVE = 'EVENT_CONTAINER_GESTURE_ACTIVE'
export const EVENT_CONTAINER_GESTURE_RELESE = 'EVENT_CONTAINER_GESTURE_RELESE'
export const EVENT_HEADER_GRANT = 'EVENT_HEADER_GRANT'
export const EVENT_HEADER_RELEASE = 'EVENT_HEADER_RELEASE'