
export const TABVIEW_TABDIDCLICK = 'TABVIEW_TABDIDCLICK'
export const TABVIEW_BECOME_RESPONDER = 'TABVIEW_BECOME_RESPONDER'
export const TABVIEW_ONSCROLL = 'TABVIEW_ONSCROLL'
export const TABVIEW_HEADER_GRANT = 'TABVIEW_HEADER_GRANT'
export const TABVIEW_HEADER_RELEASE = 'TABVIEW_HEADER_RELEASE'
export const TABVIEW_PULL_RELESE = 'TABVIEW_PULL_RELESE'
export const TABVIEW_SCENE_SCROLL_TOP = 'TABVIEW_SCENE_SCROLL_TOP'

